language: android
jdk: openjdk7
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-19
    - extra-android-m2repository
    - extra-android-support
git:
  submodules: false
before_install:
  - chmod +x gradlew
  - gem install fir-cli
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule init && git submodule update
script:
  -  ./gradlew clean build
before_deploy:
  - mv app/build/outputs/apk/app-debug.apk app/build/outputs/apk/FileExplorer.apk

after_deploy:
  - fir p app/build/outputs/apk/FileExplorer.apk -T $FIR_TOKEN -c "`git cat-file tag $TRAVIS_TAG`"
  - curl -d "appid=10948&to=allo.vince@gmail.com&subject=[自动通知] 安卓新版本$TRAVIS_TAG发布&project=u2c0r2&signature=$SUBMAIL_SIGN&vars={\"TRAVIS_REPO_SLUG\":\"$TRAVIS_REPO_SLUG\",\"TRAVIS_TAG\":\"$TRAVIS_TAG\",\"TAG_DESCRIPTION\":\"$(git cat-file tag $TRAVIS_TAG | awk 1 ORS='<br>')\"}" https://api.submail.cn/mail/xsend.json
  git:
    depth: 1